# Generated by Django 3.2.3 on 2021-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=100)),
                ('bauther', models.CharField(max_length=100)),
                ('bimage', models.CharField(max_length=150000)),
            ],
            options={
                'db_table': 'book1122',
            },
        ),
        migrations.CreateModel(
            name='Students1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'students1122',
            },
        ),
    ]
