# Generated by Django 3.2.3 on 2021-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bimage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
